#!/bin/bash
# sistema - script que mostra informações do sistema
# Autor - Eric Douglas

# Pede uma confirmação do user antes de executar
echo "Vou buscar os dados do sistema. Posso continuar? [sn] "
read RESPOSTA

# testa se foi digitado 'n', se sim, interrompe o script
test "$RESPOSTA" = "n" && exit

# Mostra data e hora corrente
echo "Data e Horário:"
date
echo

# O df mostra as partições e quanto cada uma ocupa no disco
echo "Uso do disco:"
df
echo

# O w mostra os users conectados na máquina
echo "Usuários conectados:"
w
